repositories:
- name: jupyterhub
  url: https://jupyterhub.github.io/helm-chart/


releases:

## System


- name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
    group: ingress
  chart: stable/nginx-ingress
  version: 0.28.2
  values:
  - nginx-ingress/nginx-ingress.yml


## Monitoring

- name: grafana-playground-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
  chart: ./charts/nfs-volume
  values:
  - grafana-playground/nfs-volume.yml

- name: grafana-playground
  namespace: monitoring
  labels:
    app: grafana
    group: monitoring
  chart: stable/grafana
  # Latest version has a bug https://github.com/kubernetes/charts/pull/6196
  version: 1.10.2
  values:
  - grafana-playground/grafana.yml
  - ../config/grafana-playground/grafana-secret.yml


- name: grafana-global-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
  chart: ./charts/nfs-volume
  values:
  - grafana-global/nfs-volume.yml

- name: grafana-global
  namespace: monitoring
  labels:
    app: grafana
    group: monitoring
  chart: stable/grafana
  # Latest version has a bug https://github.com/kubernetes/charts/pull/6196
  version: 1.10.2
  values:
  - grafana-global/grafana.yml
  - ../config/grafana-global/grafana-secret.yml


- name: monitoring-oauth2
  namespace: monitoring
  labels:
    app: oauth2-proxy
    group: monitoring
  # The official stable/oauth2-proxy chart doesn't work
  chart: ./charts/oauth2-proxy
  values:
  - monitoring-oauth2/oauth2-proxy.yml
  - ../config/monitoring-oauth2/oauth2-proxy.yml


- name: prometheus-k8s-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
  chart: ./charts/nfs-volume
  values:
  - prometheus-k8s/nfs-volume.yml

- name: prometheus-k8s
  namespace: monitoring
  labels:
    app: prometheus
    group: monitoring
  chart: stable/prometheus
  version: 6.7.4
  values:
  - prometheus-k8s/prometheus.yml


- name: prometheus-ome-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
  chart: ./charts/nfs-volume
  values:
  - prometheus-ome/nfs-volume.yml

- name: prometheus-ome
  namespace: monitoring
  labels:
    app: prometheus
    group: monitoring
  chart: stable/prometheus
  version: 6.7.4
  values:
  - prometheus-ome/prometheus.yml
  - ../config/prometheus-ome/prometheus.yml


- name: prometheus-global-storage
  namespace: monitoring
  labels:
    app: storage
    group: monitoring
  chart: ./charts/nfs-volume
  values:
  - prometheus-global/nfs-volume.yml

- name: prometheus-global
  namespace: monitoring
  labels:
    app: prometheus
    group: monitoring
  chart: stable/prometheus
  version: 6.7.4
  values:
  - prometheus-global/prometheus.yml
  - ../config/prometheus-global/prometheus.yml


- name: omero-grafana-ds
  namespace: monitoring
  labels:
    app: omero-grafana-json-datasource
    group: monitoring
  chart: ./charts/generic-webapp
  values:
  - omero-grafana-ds/generic-webapp.yml


## Redmine

- name: idr-redmine-storage
  namespace: idr-redmine
  labels:
    app: storage
    group: redmine
  chart: ./charts/nfs-volume
  values:
  - idr-redmine/nfs-volume.yml

- name: idr-redmine
  namespace: idr-redmine
  labels:
    app: redmine
    group: redmine
  chart: ./idr-redmine-tracker/chart
  values:
  - idr-redmine/idr-redmine-tracker.yml
  # NOTE: you must create secret manually with the current config:
  # pass show x/idr-redmine/secret-config.yaml > idr-redmine/secret-config.yaml
  # kubectl apply -f idr-redmine/secret-config.yaml


## JupyterHub

- name: jupyter-int
  namespace: jupyter-int
  labels:
    app: jupyterhub
    group: jupyterhub
  chart: jupyterhub/jupyterhub
  version: v0.7-5bd0b65
  values:
  - jupyterhub-internal/zero-to-jupyterhub-config.yml
  - ../config/jupyterhub-internal/zero-to-jupyterhub-secret.yml

- name: jupyter-itr
  namespace: jupyter-itr
  labels:
    app: jupyterhub
    group: jupyterhub
  chart: jupyterhub/jupyterhub
  version: v0.7-15e87d6
  values:
  - jupyterhub-itr/zero-to-jupyterhub-config.yml
  - ../config/jupyterhub-itr/zero-to-jupyterhub-secret.yml

- name: jupyter-train
  namespace: jupyter-train
  labels:
    app: jupyterhub
    group: jupyterhub
  chart: jupyterhub/jupyterhub
  version: v0.7-d617e0a
  values:
  - jupyterhub-training/zero-to-jupyterhub-config.yml
  - ../config/jupyterhub-training/zero-to-jupyterhub-secret.yml


## Object store

- name: minio-storage
  namespace: minio
  labels:
    app: storage
    group: objectstore
  chart: ./charts/nfs-volume
  values:
  - minio/nfs-volume.yml
  # This volume is shared with minio-slow

- name: minio
  namespace: minio
  labels:
    app: minio
    group: objectstore
  chart: ./charts/minio
  values:
  - minio/minio.yml
  - ../config/minio/minio.yml

- name: minio-slow
  namespace: minio
  labels:
    app: minio
    group: objectstore
  chart: ./charts/minio
  values:
  - minio-slow/minio.yml
  - ../config/minio-slow/minio.yml
