apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "generic-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "generic-webapp.name" . }}
    helm.sh/chart: {{ include "generic-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "generic-webapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "generic-webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "image.repository required" .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- range $value := .Values.command }}
            - {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- range $value := .Values.args }}
            - {{ $value | quote }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.internalPort }}
              protocol: TCP
        {{- if .Values.probe.liveness.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelay }}
        {{- end }}
        {{- if .Values.probe.readiness.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelay }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
